---
# ---------------------- Installing Jira in First Server--------------------#
- name: Downloading jira
  become: true
  get_url: url={{jira[jira_version].url}} dest=/opt validate_certs=no
  tags:
    - download-jira

- name: Extract jira
  become: true
  command: tar -xvzf /opt/{{jira[jira_version].file_name}} -C {{jira[jira_version].install_path}} --strip-components=1 creates={{jira[jira_version].install_path}}/bin
  tags:
    - extract-jira

- name: Set jira.home in Jira_Install_Path/atlassian-jira/WEB-INF/classes/jira-application.properties
  become: true
  lineinfile:
    path: '{{jira[jira_version].install_path}}/atlassian-jira/WEB-INF/classes/jira-application.properties'
    regexp: '^jira\.home'
    line: jira.home = {{jira[jira_version].home_path}}
  tags:
    - set-jira-home-config

- name: Copy server.xml file
  become: true
  copy:
    src: server.xml
    dest: '{{jira[jira_version].install_path}}/conf/'
  tags:
    - copy-server-file

- name: Creating cluster.properties
  become: true
  file:
    path: "{{jira[jira_version].home_path}}/cluster.properties"
    state: touch
    owner: jira
    group: jira

- name: Setting node id in cluster.properties
  become: true
  lineinfile:
    path: '{{jira[jira_version].home_path}}/cluster.properties'
    regexp: '^jira\.node\.id'
    line: jira.node.id = {{inventory_hostname}}
  tags:
    - set-jira-node-name

- name: Setting shared Home path in cluster.properties
  become: true
  lineinfile:
    path: '{{jira[jira_version].home_path}}/cluster.properties'
    regexp: '^jira\.shared\.home'
    line: jira.shared.home = {{jira[jira_version].shared_home_path}}
  tags:
    - set-jira-shared-home-config

- name: Setting ulimit in <Jira-install>/bin/setenv.sh
  become: true
  lineinfile:
    path: '{{jira[jira_version].install_path}}/bin/setenv.sh'
    regexp: '^ulimit'
    line: ulimit -n 16384
  tags:
    - set-jira-shared-home-config

- import_tasks: conf-jira-system-service.yml

- name: Create symbolic link 
  become: true
  file:
    src: "{{jira[jira_version].install_path}}"
    dest: "{{jira[jira_version].link_path}}"
    state: link
    owner: jira
    group: jira
  tags:
    - create-jira-link

# ---------------------- Installing Jira in First Server--------------------#



- name: Chown Install directory
  become: true
  file: path={{jira[jira_version].install_path}} owner=jira group=jira recurse=yes
  tags:
    - chown-install-dir
    
- name: Chown home directory
  become: true
  file: path={{jira[jira_version].home_path}} owner=jira group=jira recurse=yes
  tags:
    - chown-install-dir

- name: Chown home directory
  become: true
  file: path={{jira[jira_version].shared_home_path}} owner=jira group=jira recurse=yes
  tags:
    - chown-install-dir

