---
- name: Get jira_version_value
  debug: msg={{ jira_version }}
- name: Create Jira user
  become: true
  user:
    name: jira
    create_home: yes
    state: present
  tags:
    - create-jira-user

- name: Create Jira Installation directory if not exists
  become: true
  file: path={{jira[jira_version].install_path}} owner=jira group=jira state=directory recurse=yes
  tags:
    - create-jira-install-directory

- name: Create Jira home directory if not exists
  become: true
  file: path={{jira[jira_version].home_path}} owner=jira group=jira state=directory recurse=yes
  tags:
    - create-jira-home-directory

- name: jira download url
  debug: msg=" {{jira[jira_version].url}} "

- name: Downloading jira
  become: true
  get_url: url={{jira[jira_version].url}} dest=/opt validate_certs=no
  tags:
    - download-jira

- name: Extract jira
  become: true
  command: tar -xvzf /opt/{{jira[jira_version].file_name}} -C {{jira[jira_version].install_path}} --strip-components=1 creates={{jira[jira_version].install_path}}/bin
  tags:
    - extract-jira

- name: Set jira.home in Jira_Install_Path/atlassian-jira/WEB-INF/classes/jira-application.properties
  become: true
  lineinfile:
    path: '{{jira[jira_version].install_path}}/atlassian-jira/WEB-INF/classes/jira-application.properties'
    regexp: '^jira\.home'
    line: jira.home = {{jira[jira_version].home_path}}
  tags:
    - set-jira-home-config

- name: Copy server.xml file
  become: true
  copy:
    src: server.xml
    dest: '{{jira[jira_version].install_path}}/conf/'
  tags:
    - copy-server-file

- import_tasks: conf-jira-system-service.yml
  when: not is_upgrade | bool