---

- import_tasks: install-jira.yml
  when: inventory_hostname == 'jira1' and is_install | bool

- import_tasks: add-cluster-node.yml
  when: add_cluster_nodes | bool

- import_tasks: upgrade-jira-tasks.yml
  when: is_upgrade | bool

- set_fact: run_command="ansible -i inventory <hostname> -m systemd -a 'name=jira state=started' -u <login-username> --key-file=<private-key-file> --become"

- name: Run below command to start jira on each nodes one by one
  debug: msg="{{ run_command }}"
