# declare default variables that has lowest priority
---
# java_version: jdk8
# java_user: deploy
# java_group: deploy

jira_version: 8.3.2
upgrade_version: 8.13.2
is_install: yes
is_upgrade: no
add_cluster_nodes: no